### ISSUE TITLE
Not Working on RenderDoc 1.13

### ISSUE THREAD

**Issue by Official-Husko** [FXTD-ODYSSEY/renderdoc2fbx#2]
Can't export it. I get this error:

```
EXTN 17120 22:08:16 unknown(0) Error Traceback (most recent call last):                
EXTN 17120 22:08:16 unknown(0) Error File "C:/Users/.../AppData/Roaming/qrenderdoc/extensions\exporter\fbx\__init__.py", line 487, in prepare_export
EXTN 17120 22:08:16 unknown(0) Error dialog = QueryDialog(mqt)                         
EXTN 17120 22:08:16 unknown(0) Error File "C:/Users/.../AppData/Roaming/qrenderdoc/extensions\exporter\fbx\query_dialog.py", line 47, in __init__
EXTN 17120 22:08:16 unknown(0) Error self.template_select(0)                           
EXTN 17120 22:08:16 unknown(0) Error File "C:/Users/.../AppData/Roaming/qrenderdoc/extensions\exporter\fbx\query_dialog.py", line 51, in template_select
EXTN 17120 22:08:16 unknown(0) Error text = self.combo.itemText(index)                 
EXTN 17120 22:08:16 unknown(0) Error AttributeError: 'QueryDialog' object has no attribute 'combo'
```
